development:
  adapter: postgresql
  encoding: unicode
  database: hours_report_development
  host: localhost
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hours_report_test
  host: localhost
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  variables:
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    tcp_keepalives_count: 100
